import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

// Replaces the `eslintConfig: { extends: ['react-app'] }` block that lived in
// package.json. That preset came from eslint-config-react-app, a react-scripts
// dependency removed with CRA — and it pins ESLint 8, so adopting it standalone
// would mean going backwards from flat config.
export default tseslint.config(
  {
    ignores: [
      'build/**',
      'node_modules/**',
      // Generated by graphql-codegen; lint findings here are not actionable
      // without changing codegen.yml.
      'src/graphql/types.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.es2021 },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // Severities tuned to match what CRA's `react-app` preset reported, so
      // this script surfaces the same pre-existing debt rather than inventing a
      // new failing gate. These are all real signal — they are warnings, not
      // "off", so `yarn lint` stays informative and exits 0.
      //
      // Fixing them is tracked as a follow-up; doing it here would mix
      // unrelated changes into a toolchain migration.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      // Both new in eslint-plugin-react-hooks 7; CRA's older plugin had no such
      // rules, so every hit is pre-existing code that predates the check.
      'react-hooks/set-state-in-effect': 'warn',
      // Currently one hit: SplitButton.tsx reads anchorRef.current during
      // render. A real anti-pattern, but it is also MUI's own documented Popper
      // pattern, so it needs a considered fix rather than a drive-by one.
      'react-hooks/refs': 'warn',
    },
  },
);
